### ISSUE TITLE
V2rayN生成的节点链接中host和sni多带了https://

### ISSUE THREAD

**Issue by clift190** [fscarmen/ArgoX#1]
安装确实非常的省心，发现不通时查看发现多了https://头，去掉就通了。
这个Argo的速度也很一般般吧，油管有3、4千，于是又套了个cf的反代，发现速度乱跳，一会1千多，一会1万多，是无固定域名安装。

**Comment by fscarmen2** [comment]
谢谢，今天我也发现这个问题了，今晚将会更新内容，十分颠覆性。
