### ISSUE TITLE
can you please add V2Board

### ISSUE THREAD

**Issue by umairsali07** [fscarmen/ArgoX#12]
can you please add V2Board Support
like https://github.com/3Kmfi6HP/argo-airport-paas

**Comment by fscarmen** [comment]
I have never been exposed to v2board before, so I don't have a supported timeline at the moment. Pull requests are welcome.

**Comment by dawei77775** [comment]
节点导入V2RAYN和小火煎可以使用，导入PASSWALL无法使用

**Comment by fscarmen** [comment]
> 节点导入V2RAYN和小火煎可以使用，导入PASSWALL无法使用

照顾不了那么多客户端了，请用户根据参数，自行手动填写。
