### ISSUE TITLE
显示下载失败的问题

### ISSUE THREAD

**Issue by GD2021** [fscarmen/ArgoX#13]
![image](https://github.com/fscarmen/ArgoX/assets/81171294/f5ce6673-1f2d-4cf5-8a54-df2d6099d7cd)

还有疑问：这个地方填一个还是两个？我是不是只填入sing
![image](https://github.com/fscarmen/ArgoX/assets/81171294/9a1378ac-983a-4b35-b043-659c26434c0d)
![image](https://github.com/fscarmen/ArgoX/assets/81171294/df939b9f-b8a0-4ca1-8caa-6e6a0092c92f)

**Comment by fscarmen2** [comment]
我刚才安装过成功的，你再多试一次

第二个问题，你是输入 sing ，即可，出来的链接，你要选  zctou.link 的域名

**Comment by fscarmen** [comment]
Github 反代加速网站 https://ghproxy.com 是 CNAME 到 *.ops.ci 的不同节点上的，然后整个 ci 炸了，导致用不了。
现在已经去除该代理，请再试试。

**Comment by fscarmen** [comment]
```
wget -O argox.sh https://raw.githubusercontent.com/fscarmen/ArgoX/main/argox.sh; sed -i '/ghproxy.com/s/^.*/#&/g' argox.sh; bash argox.sh
```
