### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by fomsun** [fscarmen/ArgoX#14]
<img width="777" alt="image" src="https://github.com/fscarmen/ArgoX/assets/54971536/8a04b2d2-4ca7-4b21-8dd5-33f3f80603c0">
脚本显示xia'z下载失败 重试了三次都是一样的效果

**Comment by fomsun** [comment]
并且脚本运行特别慢 测试过 vps没有问题

**Comment by fscarmen** [comment]
Github 反代加速网站 https://ghproxy.com 是 CNAME 到 *.ops.ci 的不同节点上的，然后整个 ci 炸了，导致用不了。
现在已经去除该代理，请再试试。

**Comment by zexry619** [comment]
I also experienced this, any solution for this?

**Comment by fscarmen** [comment]
```
wget -O argox.sh https://raw.githubusercontent.com/fscarmen/ArgoX/main/argox.sh; sed -i '/ghproxy.com/s/^.*/#&/g' argox.sh; bash argox.sh
```

**Comment by fomsun** [comment]
Thanks
