### ISSUE TITLE
IPv6 only 机器遇到 argo.sh: line 455: /tmp/argox/xray: No such file or directory 下载错误 -【原因: Github 不完全支持 IPv6。解决方案: 1. 使用 nat64 dns 2. 使用 warp】

### ISSUE THREAD

**Issue by f1shh1** [fscarmen/ArgoX#21]
/dev/fd/63:行455: /tmp/argox/xray: 没有那个文件或目录

 下载最新版本 ARGO 失败，脚本退出，问题反馈:[https://github.com/fscarmen/argox/issues]

**Comment by fscarmen** [comment]
你是升级的时候失败还是安装的时候失败？今天我加了github proxy

**Comment by fscarmen** [comment]
你是升级的时候失败还是安装的时候失败？今天我加了github proxy

**Comment by f1shh1** [comment]
> 你是升级的时候失败还是安装的时候失败？今天我加了github proxy

之前几次还是可以的，我卸载重装了一次就这样了

**Comment by cnuAs** [comment]
我也是这样的情况

**Comment by fscarmen** [comment]
> 我也是这样的情况

现在还是这样吗？如果不行，把ssh信息发我 fscarmen@gmail.com 看看

**Comment by f1shh1** [comment]
> fscarmen@gmail.com

发你了，007001008gmail

**Comment by fscarmen** [comment]
> > [fscarmen@gmail.com](mailto:fscarmen@gmail.com)
> 
> 发你了，007001008gmail

是这台吗？2a12:******:c9d8

**Comment by fscarmen** [comment]
> > [fscarmen@gmail.com](mailto:fscarmen@gmail.com)
> 
> 发你了，007001008gmail

已处理了，dns 服务器的问题，github 不完全支持 IPv6 ，而你的机器是 IPv6 only 的，原来的 nameserver 如下   
nameserver 4.2.2.1
nameserver 4.2.2.2
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844

以上所有的都解析不了 github ，导致下载失败。
同时有点奇怪的是，你的 v6 only 机器，居然是 v4 的 nameserver 在最开头的，日常使用也会有不少问题的。

现处理方法，把你原来的 nameserver 文件备份到 /etc/resolv.conf.bak (即是上面的内容)，使用新的支持 nat64 的 nameserver，具体指令如下
```
echo -e "nameserver 2a00:1098:2b::1\nnameserver 2a01:4f9:c010:3f02::1\nnameserver 2a01:4f8:c2c:123f::1\nnameserver 2a00:1098:2c::1" > /etc/resolv.conf
```

现在你的 nameserver 如下
nameserver 2a00:1098:2b::1
nameserver 2a01:4f9:c010:3f02::1
nameserver 2a01:4f8:c2c:123f::1
nameserver 2a00:1098:2c::1

**Comment by fscarmen** [comment]
另外的解决方案是安装 warp 以获取 IPv4 出局
```
wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh && bash menu.sh 4
```

**Comment by fscarmen** [comment]
> ``[root@zzzxxx ~]# bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/argox/main/argox.sh) [root@zzzxxx ~]# wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh && bash menu.sh 4 --2023-11-17 07:51:59-- https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh 正在解析主机 gitlab.com (gitlab.com)... 失败：未知的名称或服务。` 老哥昨天输入指令能弹出来安装包的今天弹不出那个安装界面了，还有安装warp好像安装不了

请处理一下机器的dns

**Comment by cnuAs** [comment]
老哥现在ok了

**Comment by fscarmen** [comment]
> 老哥现在ok了

也是这个问题吗？

**Comment by cnuAs** [comment]
我重装vps了，不知道是不是这个问题，我不是很懂这个

fscarmen ***@***.***> 于2023年11月18日周六 13:19写道：
