### ISSUE TITLE
 下 载 最 新 版 本  ARGO 失 败 ， 脚 本 退 出 ， 问 题 反 馈 :[https://github.com/fscarmen/argox/issues]-【已解决：Github 代理 gh-proxy.com 出问题了，mirror.ghproxy.com】

### ISSUE THREAD

**Issue by a7541** [fscarmen/ArgoX#22]
下 载 最 新 版 本  ARGO 失 败 ， 脚 本 退 出 ， 问 题 反 馈 :[https://github.com/fscarmen/argox/issues]

ipv6 带ipv4出口的.之前一直稳定安装的，突然就安装不了

**Comment by fscarmen** [comment]
Github 代理 https://gh-proxy.com/ 出问题了，我换成 https://mirror.ghproxy.com/ 解决了
