### ISSUE TITLE
https://fscarmen.cloudflare.now.cc/这个地方没有获取token的链接了

### ISSUE THREAD

**Issue by zxjack** [fscarmen/ArgoX#24]
https://fscarmen.cloudflare.now.cc/这个地方没有获取token的链接了，无法获取授权的获得token
<img width="654" alt="aogo" src="https://github.com/fscarmen/ArgoX/assets/9455090/dcf8d08c-a2fa-43e3-8d71-aa98112a07d1">

**Comment by fscarmen** [comment]
重置了一下，你看看
