### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by farhadsaberi** [fscarmen/ArgoX#26]
Hello,
My configuration is 1GB RAM - 2 core CPU.
After usage for about 4 days, the average RAM consumption reaches 1GB with around 30 users.
If I don't use Argo Tunnel, there's no issue, and everything is completely stable.
Is there any memory leak problem? Because when I execute the 'stop' command, the RAM usage returns to normal.

**Comment by fscarmen** [comment]
It is possible that the situation exists, and I also need to ask Cloudflared officials to see how to limit it!

**Comment by fscarmen** [comment]
It is possible that the situation exists, and I also need to ask Cloudflared officials to see how to limit it!

**Comment by fscarmen** [comment]
https://github.com/cloudflare/cloudflared/issues/1129
