### ISSUE TITLE
重启VPS以后卡在 所有依赖已存在，不需要额外安装 

### ISSUE THREAD

**Issue by peleopard** [fscarmen/ArgoX#27]
重启VPS后运行脚本以后卡在 所有依赖已存在，不需要额外安装  一直进行下一步操作

重启之前已经成功安装了argox  跟hy2  并且测试节点都是通的 就是重启后再运行脚本运行不了了 怎么回事？

 一直卡在所有依赖已存在，不需要额外安装

**Comment by fscarmen** [comment]
什么系统？卡在哪步？实在不行卸载重装
