### ISSUE TITLE
How to send through IPV4?

### ISSUE THREAD

**Issue by aminraymi** [fscarmen/ArgoX#28]
Hi, my server has two IPs IPV4 and IPV6, but ArgoX uses ipv6, and google have problem with that, how can I force it to use ipv4 only,
Thanks

**Comment by fscarmen** [comment]
1. You add a GLOBAL OPTIONS `--edge-ip-version 4` to Cloudflared.
2.  https://xtls.github.io/en/document/level-2/redirect.html
