### ISSUE TITLE
当前架构 amd64 暂不支持

### ISSUE THREAD

**Issue by 6uu1** [fscarmen/ArgoX#3]
请求支持amd64

**Comment by fscarmen** [comment]
请再详细点说说，我都是用amd64机器测试的

**Comment by fscarmen** [comment]
抱歉，是我粗心， amd64 一般显示 x86_64 这样，我一下子没有反应过来，有的vps会显示 amd64 ，已处理，请再试试。

**Comment by 6uu1** [comment]
好的，发现问题了，那台机子是freebsd系统的，我发现 xray有freebsd的内核，是否可以进行适配呢？

**Comment by fscarmen** [comment]
> 那台机子是freebsd系统的，我发现 xray有freebsd的内核

我理解 freebsd 是操作系统，而 xray 和 cloudflared 的版本是针对架构的（如amd64/arm64/s390x)，所以关键点是要了解 freebsd 的系统，但我从来没有使用过这个系统，你是有特殊的需求一定要在该系统部署吗？否则我建议你换三大系统可能更来得容易。

**Comment by 6uu1** [comment]
> > 那台机子是freebsd系统的，我发现 xray有freebsd的内核
> 
> 我理解 freebsd 是操作系统，而 xray 和 cloudflared 的版本是针对架构的（如amd64/arm64/s390x)，所以关键点是要了解 freebsd 的系统，但我从来没有使用过这个系统，你是有特殊的需求一定要在该系统部署吗？否则我建议你换三大系统可能更来得容易。

对，因为某个平台只支持freebsd😂

**Comment by fscarmen** [comment]
> 对，因为某个平台只支持freebsd😂

抱歉，暂时没有计划支持 freebsd。
