### ISSUE TITLE
导出sing-box的reality无法连接

### ISSUE THREAD

**Issue by FeulerLoup** [fscarmen/ArgoX#35]
https://github.com/fscarmen/ArgoX/blob/f3f89d1586b2aabe8334e64067be01226c8cd04b/argox.sh#L1028
https://github.com/fscarmen/ArgoX/blob/f3f89d1586b2aabe8334e64067be01226c8cd04b/argox.sh#L1049

这里是不是应该用$REALITY_PUBLIC

**Comment by fscarmen** [comment]
是的，已经改了，谢谢！用户量还是不够啊，这些错误已经3个月了，才有用户指出来。
祝春节快乐！身体健康！万事胜意！

**Comment by FeulerLoup** [comment]
第一次见写的这么工整的脚本，学到了不少东西。
感谢开源，新年快乐！
