### ISSUE TITLE
problem with 用户可以通过 Cloudflare Json 生成网轻松获取: https://fscarmen.cloudflare.now.cc

### ISSUE THREAD

**Issue by mamadjb** [fscarmen/ArgoX#37]
嗨，当我尝试使用这个网站https://fscarmen.cloudflare.now.cc时，当我将我的子域名放在tunnel1中，它显示了Cloudflare授权。当我点击选择域名时，它显示了以下消息：
"These rules must pass for { "name": "Argo Tunnel API Token for example.com in email.com's Account", "creation_type": "custom", "policies": { { "effect": "allow", "resources": ..., "permission_groups": ... } } } - name must have a length between 1 and 120 (Code: 400)"
我的域名有63个字符。

**Comment by fscarmen** [comment]
我试了一下63个字符可以的，是不是你的还包含了特殊的，你再换些全字母+数字的看看。
<img width="801" alt="image" src="https://github.com/fscarmen/ArgoX/assets/62703343/3a573296-0c6a-43c1-9376-0038abb9dba5">

<img width="1679" alt="image" src="https://github.com/fscarmen/ArgoX/assets/62703343/073db735-4210-4263-8444-0a000440eda3">

**Comment by mamadjb** [comment]
您好，我想您误解了。我的域名有 63 个字符，我的子域名有 5 个字符。我正在使用 Google 翻译编写此文本。
![1](https://github.com/fscarmen/ArgoX/assets/117049306/a2a1e372-a3fa-4b81-be87-dd30f61803f8)
![2](https://github.com/fscarmen/ArgoX/assets/117049306/a492b2fb-ce10-4985-b9f9-1c386a243acb)
![3](https://github.com/fscarmen/ArgoX/assets/117049306/7b90bf8e-6a7c-4166-b9fe-f097e2cf1edf)

**Comment by mamadjb** [comment]
抱歉跨域，我这样做是出于安全原因

**Comment by fscarmen** [comment]
这个报错是 cf 官方的提示的，我也是第1次见，同时也处理不了，估计与你使用的域名过长有关。
