### ISSUE TITLE
经常自动退出

### ISSUE THREAD

**Issue by shentong0722** [fscarmen/ArgoX#38]
![image](https://github.com/fscarmen/ArgoX/assets/63089521/b60ca76f-012f-4936-bc67-29988cd40c97)
Argo经常自动退出，无法后台保持运行

**Comment by fscarmen** [comment]
systemd 里写了 Restart=on-failure，遇到非正常退出，应该会重启才对，你是什么系统和机器是多少内存的？

**Comment by shentong0722** [comment]
我在四台机器上都装了，最低配置的是Alpine Linux 内存256MB，最高配的是Ubuntu 20 TLS 内存2GB
四台机器都遇到了频繁退出问题，
是会重启，但是这对于日常使用有很大的影响，经常断连啊，重启一般也要好几分钟

**Comment by fscarmen** [comment]
近2天时间了，隧道和进程都没有变，即是 argo 没有退出，所以不太清楚你那里的情况了。
![image](https://github.com/fscarmen/ArgoX/assets/62703343/378887b5-705c-4976-8ba0-4e819471a599)

**Comment by fscarmen** [comment]
第4天了，argo 隧道和进程都仍然稳定，后续不再跟踪了。建议你重置或者 dd 一个新系统，不要安装其他服务试试。
![image](https://github.com/fscarmen/ArgoX/assets/62703343/92ee453b-15ba-4e26-91a3-22882862b10d)
