### ISSUE TITLE
fscarmen.cloudflare.now.cc点击submit无反应

### ISSUE THREAD

**Issue by la0wei** [fscarmen/ArgoX#4]
后台服务出问题了吗？
使用临时隧道用了一下，速度飞快！

**Comment by fscarmen** [comment]
我刚试可以哦，你再试试呢。
<img width="784" alt="image" src="https://user-images.githubusercontent.com/62703343/226169918-6645fdea-930c-4e13-9b4f-e31714941c0c.png">

**Comment by la0wei** [comment]
> 我刚试可以哦，你再试试呢。 <img alt="image" width="784" src="https://user-images.githubusercontent.com/62703343/226169918-6645fdea-930c-4e13-9b4f-e31714941c0c.png">

谢谢解答。用f12查看，有内容是ns_binding_aborted，不知道是firefox的兼容问题还是什么，网络上挺多的，换成chrome就可以了。
第一次使用是可以生成的。但是cloudflare的后台token名称是一样的，都是Argo Tunnel API Token for domain in xxx's Account。为了便于区分，我把token删除，接着cloudflare可以生成，但网站似乎获取不了token，文本框显示  Error: All tunnel creation failed. 
已经使用chrome隐私模式，未开启插件，网站看f12是正常的，有一个请求在pending，应该是等待cloudflare回传信息。

**Comment by la0wei** [comment]
补充DP。
在我反复尝试中，cloudflare是可以持续创建删除token的，不像是我多次创建的问题。
想到换个token名称再试，这次一把就成功了

**Comment by la0wei** [comment]
没有:(
1.对交互模式中使用的参数不确定，不明白具体指代，比如xray server。
2.改用config文件，把对应的参数都填过了，生成的配置导入v2rayn，但是传输过程中报错
3.目前使用的是脚本提供的临时域名，可以正常工作，高峰期延迟稍高，但带宽多线程下载能到100mbps，非高峰期youtube1080P视频进度条可以即点即播。
4.使用的是一个三级域名，在cloudflare的dns页，显示This hostname is not covered by a certificate，不知道是否与此有关。
5.可能之前使用火狐生成tunnel的时候，没有json文件生成，但是dns解析的值有了，删tunnel，dns并没有同步删除。周末对这点测试下，用dns记录干净的域名操作

**Comment by la0wei** [comment]
回复下进展，一次部署成功。
有可能是在网页复制token的时候，复制了}后的一个空格，不知道脚本里有没有对这种情况的处理。
另外建议在生成链接信息的时候，把服务器IP的信息也添加进去。
比如我在同一个服务商有多个vps，如果不记录的话，会忘记是在哪台服务器部署了服务。
当然这不是脚本本身的问题，有当然更好

**Comment by fscarmen** [comment]
> 有可能是在网页复制token的时候，复制了}后的一个空格，不知道脚本里有没有对这种情况的处理。

谢谢你的建议，现在暂时没有这个处理，这两天我加这样的判断，如果是json的话，必须以 { 开头和 } 结束，一旦漏了就提示



> 比如我在同一个服务商有多个vps，如果不记录的话，会忘记是在哪台服务器部署了服务。

像这样的情况，你原隧道二级域名那里做个区分我想应该可以了吧，比如 jp-oracle/kr-oracle 又或者是IP的D段 105-gcp / 208-gcp 这样来区分。又或者你想如何，能截个图或者举个具体的例子来说明吗？

**Comment by la0wei** [comment]
![image](https://user-images.githubusercontent.com/3761308/227698356-8acb2343-c462-40f6-8750-d7eb2e4dce13.png)
图为使用脚本提供的**临时域名**生成的链接导入v2rayN后的信息

1.使用自己域名的话，可以在生成的链接文件中找到域名，可以在dns服务商处找到对应的IP，这个不太直观，但是确实是可以查找的。或者域名中包含vps的ip信息，这个更方便点，不过是在实际使用后发现的，第一次运行脚本不会意识到这一点。
![image](https://user-images.githubusercontent.com/3761308/227699281-d7234401-0954-49e8-8427-c8d0e9f2397b.png)


2.另外，网站生成token的时候，cloudflare里的api token 名称是一样的，都是Argo Tunnel API Token for domain in xxx's Account，不知道是否和二级域名关联，若是的话，则无法区分对应的域名。


2.脚本中xray server是具体要求输入什么信息呢？脚本前一步已经输入了自己的域名，此处只敢选默认。根据运行结果，该字段对应的是导出链接中的地址。通常，在v2rayN中配置成其他网站域名是为了优选cloudflare的IP，不必是自己vps的域名。
如果像我第一次部署未成功的话，可能会使用脚本提供的临时域名，此时无论伪装域名还是SNI处都无法知道是具体哪台vps的。

**Comment by fscarmen** [comment]
脚本中xray server是填你优选的ip，如不填就用个万能的icook.hk，这个不保证速度。但起码能测试节点是否能够通。

域名是填你生成隧道的域名，你不填，脚本下步就不问json或token变量，直接用临时的隧道了。不过这个不太好，机器重启的话隧道是试用，就会像你之前说的很难分得清哪台机器，所以建议还是用固定的域名，你在二级域名的时候定义好，自己分得清楚就可以了。
