### ISSUE TITLE
重启后再次运行获取节点和重启之前不一样

### ISSUE THREAD

**Issue by loohalh** [fscarmen/ArgoX#40]
重启后再次运行获取节点和重启之前不一样，重启之前节点转换后的订阅链接无法使用

**Comment by fscarmen** [comment]
进去vps 按一次 `argox -n`，订阅就会更新了。如果经常重启的话，建议用固定隧道。

**Comment by loohalh** [comment]
> 进去vps 按一次 `argox -n`，订阅就会更新了。如果经常重启的话，建议用固定隧道。

原来这样 明白了 我写个自动任务，重启后，自动执行argox -n任务
