### ISSUE TITLE
5个优选域名只有csgo可以用

### ISSUE THREAD

**Issue by JunzheJosephZhu** [fscarmen/ArgoX#46]
我是用trojan协议，试了第一个(cn...edu),第二个(who.int)和第五个(csgo)优选域名。在手机上都能用，但是用linux的clash的话只能连上用csgo域名生成的

**Comment by JunzheJosephZhu** [comment]
I tried another 2 random domains. Setting the preferred domain to baidu.com works, while setting it to 4399.com doesn't. I suspect it has something to do with GFW not having the capacity to examine all traffic directed to csgo.com/baidu.com, but more heavily inspects traffic sent to minor sites?

**Comment by JunzheJosephZhu** [comment]
我试了baidu.com,twitter.com,4399.com,都不行，只有csgo.com才能连上trojan协议

**Comment by fscarmen** [comment]
与trojan无关的，你找些 cf 支持的 cdn

**Comment by JunzheJosephZhu** [comment]
好的谢谢，我研究了一下，https://github.com/yonggekkk/Cloudflare-workers-pages-vless这里的脚本可以找到好用的优选域名

**Comment by fscarmen** [comment]
icook.hk
icook.tw
time.is
uicdn.cf
r2wind.com
cf.515188.xyz
cf.13d7s.site
default.cfnode.eu.org
v4.cfnode.eu.org
v6.cfnode.eu.org
xn--b6gac.eu.org
time.cloudflare.com
www.who.int
ip.sb
malaysia.com
russia.com
singapore.com
www.visa.com.hk
www.visa.co.jp
www.gco.gov.qa
www.gov.se
www.gov.ua
www.digitalocean.com
www.shopify.com
www.whoer.net
www.whatismyip.com
www.hugedomains.com
www.4chan.org
www.udemy.com
www.baipiao.eu.org
malaysia.com
russia.com
singapore.com
log.bpminecraft.com
www.boba88slot.com
gur.gov.ua
www.zsu.gov.ua
www.iakeys.com
www.d-555.com
yx.887141.xyz
freeyx.cloudflare88.eu.org
8.889288.xyz
cf-st.annoy.eu.org
achk.cloudflarest.link
cnamefuckxxs.yuchen.icu
cf.877771.xyz
cf.345673.xyz
cdn.didi8.com
cn.azhz.eu.org
dash.cloudflare.com
skk.moe
visa.com

**Comment by fscarmen** [comment]
更换了一些，应该都可用的。
