### ISSUE TITLE
端口被封，请问如何更改例如443端口

### ISSUE THREAD

**Issue by lieying8** [fscarmen/ArgoX#47]
端口被封，请问如何更改，例如443端口

**Comment by fscarmen** [comment]
重新安装，一开始就让输入端口啦。

**Comment by lieying8** [comment]
> 重新安装，一开始就让输入端口啦。

vl   vm   tr默认安装的均是443端口，重新安装过程中并没有要求输入端口号，只有reality默认安装提示有输入端口号

**Comment by fscarmen** [comment]
那个是使用cdn的，443是你连 cf cdn 的端口，这个与你的vps端口被封完全没有关系的，使用 cdn，是隐藏了你的vps ip的，所以不存在ip或者端口被墙的说法的，如果你的不通，就换一个优选域名或者ip即可。
