### ISSUE TITLE
[有趣的发现]

### ISSUE THREAD

**Issue by QAQ5555** [fscarmen/ArgoX#48]
修改UA以后发现auto订阅不上了，域名后还自动加上3006端口，网站打不开了，我还以为出什么问题了，一顿操作发现是UA改了无法识别，给我整笑了

**Comment by fscarmen** [comment]
是，auto是根据客户端默认的UA来判断的，如改了就访问不了，这时你可以使用各客户端的链接，那个就没判断UA了
