### ISSUE TITLE
 (8/8) 请输入节点名称 (默认为 kuyz):  /dev/fd/63: line 727: /tmp/argox/xray: No such file or directory

### ISSUE THREAD

**Issue by kuyz123** [fscarmen/ArgoX#49]
(8/8) 请输入节点名称 (默认为 kuyz): 
/dev/fd/63: line 727: /tmp/argox/xray: No such file or directory

**Comment by fscarmen** [comment]
处理连接 github 的问题

**Comment by fscarmen** [comment]
我加了 github cdn 反代，你试试再安装。
