### ISSUE TITLE
请问生成的icook.hk域名是否应该换成trycloudflare.com的随机域名才能连接

### ISSUE THREAD

**Issue by vilianfung** [fscarmen/ArgoX#5]
你好，不知道icook.hk在生成域名里面 是不是作为中转服务器，但在国内访问不了，这里是不是可以直接设置为trycloudflare.com的随机域名？

**Comment by fscarmen** [comment]
可以填 trycloudflare.com，不过这个不快的，建议你在油管或者谷歌搜个 优选IP 的视频教程，用那个快得多

**Comment by tedyang1234** [comment]
为什么我觉得argo-xray的链接比直接用x-ui建的链接慢几百毫秒，用的同样的优选ip，这个是跟自己的网络有关系吗？

**Comment by fscarmen** [comment]
> 为什么我觉得argo-xray的链接比直接用x-ui建的链接慢几百毫秒，用的同样的优选ip，这个是跟自己的网络有关系吗？

你要相同的机器，相同的优选，相同的时间，测几次数据对比才比较准确的。
