### ISSUE TITLE
新手，请教一个问题

### ISSUE THREAD

**Issue by wakaka-sam** [fscarmen/ArgoX#54]
跑完脚本后，没法使用，下面是详细描述，希望有好心人能解答一下

跑完脚本后，会有该提示以及对应二维码

>自适应 Clash / V2rayN / NekoBox / ShadowRocket / SFI / SFA / SFM 客户端:
模版:
https://junior-emissions-weights-invoice.trycloudflare.com/180565cb-780d-4d5e-be1f-a55137acd66b/auto

但是使用客户端扫描或者直接访问，都返回失败：
> 502 Bad Gateway
Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared

然后我看脚本还会返回一个链接，我从外网无法访问，但是我看 netstat这个应该是有开的才对。
*******************************************

 临时隧道域名可以从以下网站获取: http://我的 ip 地址:3333/quicktunnel 

 脚本当天运行次数: 199，累计运行次数: 218650 

root@iZt4n8zqpjrbobu4ck8l5kZ:/home/admin# sudo netstat -tlnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:24906           0.0.0.0:*               LISTEN      9662/python3        
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      13138/xray          
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      732/sshd: /usr/sbin 
tcp        0      0 127.0.0.1:3001          0.0.0.0:*               LISTEN      13138/xray          
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      6639/exim4          
tcp        0      0 127.0.0.1:3002          0.0.0.0:*               LISTEN      13138/xray          
tcp        0      0 127.0.0.1:3003          0.0.0.0:*               LISTEN      13138/xray          
tcp        0      0 127.0.0.1:3004          0.0.0.0:*               LISTEN      13138/xray          
tcp        0      0 127.0.0.1:3005          0.0.0.0:*               LISTEN      13138/xray          
tcp6       0      0 :::22153                :::*                    LISTEN      13138/xray          
tcp6       0      0 ::1:25                  :::*                    LISTEN      6639/exim4          
tcp6       0      0 :::3333                 :::*                    LISTEN      14240/cloudflared

**Comment by Aliorpse** [comment]
我是给的模板链接空白

**Comment by fscarmen** [comment]
看看nginx的服务端口有没对应上

**Comment by fscarmen** [comment]
好像没看到nginx的监听端口

**Comment by wakaka-sam** [comment]
@fscarmen 我这边没配置 nginx，直接通过端口裸连。没有 nginx 也没啥问题吧

**Comment by fscarmen** [comment]
没有nignx，那就不能订阅啊
