### ISSUE TITLE
argo节点无法使用

### ISSUE THREAD

**Issue by xiaopangzi13140** [fscarmen/ArgoX#55]
从昨天开始，脚本部署的argo节点不能使用，用了不同的优选ip也不行。脚本生成的几个节点当中，就只有前面2个节点可用，后面的3个节点(ss节点不算)都无法使用。

**Comment by vv0722** [comment]
全部不可用，希望大佬看看咋回事

**Comment by xuconnery** [comment]
+1 今天又重新部署一遍，还是不行

**Comment by qiqiqiao** [comment]
+10086 一大早起来发现节点都挂了，好像cloudflare把临时隧道停服了

**Comment by JunzheJosephZhu** [comment]
+1

**Comment by fscarmen** [comment]
本周都在忙，都没时间碰电脑，预计要下周一，二才有时间看看什么问题，据各位反馈，直连的2个可以，用cdn的4个不行是吧？是只有临时隧道不行，还是包括json和token tunnel都不行？

**Comment by xuconnery** [comment]
我是临时隧道，vless套cf，直连没试过

**Comment by xuconnery** [comment]
> 前几天就已经恢复了
> 
> > 我是临时隧道，vless套cf，直连没试过

额，好的，我重新试下

**Comment by fscarmen** [comment]
是的，已经恢复了，我试过了，不行再告诉我。
