### ISSUE TITLE
牛逼

### ISSUE THREAD

**Issue by 824779723p** [fscarmen/ArgoX#6]
一个机子搭的argox跟x-ui速度没差多少主要是几秒搞定太给力了

**Comment by fscarmen** [comment]
x-ui 优点是能搭建直连的方案，而且有个比较好操作的dashboard。而 argox 优点是安全，快，省资源，不需要申请证书，但缺点是没有处理直连的方案，都是走cdn

**Comment by Benjamin1919** [comment]
> x-ui 优点是能搭建直连的方案，而且有个比较好操作的dashboard。而 argox 优点是安全，快，省资源，不需要申请证书，但缺点是没有处理直连的方案，都是走cdn，如果是cdn的话，速度肯定优于x-ui的方案的。

大佬请教一下，可以在已经安装了xray-core的VPS上使用该脚本吗？目前我的VPS上使用的是xray的reality，另外我也通过你的WARP脚本安装了wireproxy监听本地40000然后用xray分流，不知道会不会与脚本冲突
