### ISSUE TITLE
冒昧问一下，此脚本是否适合ipv6 only VPS运行

### ISSUE THREAD

**Issue by longxx** [fscarmen/ArgoX#9]
貌似我没找到pv6搭Xray节点比较合适的方案，看介绍感觉可以？

**Comment by fscarmen** [comment]
最好一并安装 warp ，试试

**Comment by longxx** [comment]
今天一键安装试了一下，用不用优选IP，速度比我ipv6直连都要高一些，优选ip似乎只影响ping值。不知道如何自定义隧道那些，速度会不会更快。总之很不错，感谢

**Comment by longxx** [comment]
使用该脚本造成cfw临时或者地区性阻断，原因不明。ipv6
